import React from 'react'

export default function About() {
  return (
    // This is a sample About Page text
    <div style={{ paddingRight: "10vw", paddingLeft: "10vw", textAlign: "justify" }}>
      <h2>About Page</h2>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. A recusandae earum eum, quas voluptas optio voluptate tenetur culpa sapiente. Laborum exercitationem modi quo adipisci sed, reprehenderit quia? Architecto minima expedita accusamus ex, ad nemo exercitationem, blanditiis eligendi perferendis aspernatur optio numquam rem ullam veniam corporis debitis illum ipsam aut nesciunt odit? Et neque, sunt animi ipsa fugit porro sit nemo laborum minus aliquid magni iusto! Numquam vitae possimus voluptates molestias aspernatur distinctio eaque, explicabo inventore. Quidem aliquam totam a? Commodi amet distinctio blanditiis quam, facere illo? Tempore fuga enim provident dolor illo nesciunt error ratione quae earum, autem nobis at doloremque? Tempore architecto est nobis pariatur similique, nulla numquam nesciunt quibusdam iure odit voluptates facere fugiat fuga quia. Quasi facere exercitationem doloribus sit aliquam itaque voluptatum ipsa soluta nesciunt officia earum, nisi ex commodi quaerat aspernatur dignissimos temporibus suscipit, numquam reiciendis nulla excepturi magnam! Optio ut delectus nisi fuga qui, deleniti quisquam saepe laudantium explicabo sequi dignissimos dolores officia commodi. Saepe recusandae rerum voluptas ullam perspiciatis ipsa illum, tenetur, expedita distinctio omnis sint reprehenderit natus, quibusdam voluptate sapiente iste dolorum. Perferendis sit aliquid natus iusto tempore error ratione, cumque cum perspiciatis doloremque dolore, excepturi nesciunt qui facere exercitationem obcaecati! Ipsam.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur quasi ipsum ab necessitatibus exercitationem voluptate odio corrupti assumenda magni, perferendis eius veniam accusantium, nam, eveniet nemo quisquam doloremque! Eveniet iusto harum assumenda nisi quis mollitia adipisci natus obcaecati illum iste praesentium dolorum, cumque eaque provident vero libero molestias delectus tenetur molestiae corporis voluptatibus cum laboriosam. Nobis sit vero voluptatem suscipit! Hic, est vel! Beatae labore, obcaecati consequuntur eveniet, deserunt sint illum accusantium veniam officia consectetur quis. Inventore consequuntur consectetur molestias.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid in nam dolorum inventore ipsam nemo velit asperiores minima earum officiis, illum commodi molestiae nesciunt ad esse eveniet quo aliquam, fugit incidunt recusandae ipsa provident! Ipsa corporis, nulla cum molestiae temporibus debitis iusto iste, suscipit quae excepturi quibusdam consequatur tenetur sequi illum est. Dolore sed, excepturi molestiae ipsa aliquid facere expedita, odit corrupti quaerat fugiat atque itaque, similique eum odio sit hic velit voluptas quia tempora animi? Dolorum eum sequi ea facere repudiandae adipisci nemo quae aperiam. Exercitationem, in beatae. Assumenda aliquid commodi porro impedit eveniet, quas placeat voluptas amet temporibus odit laborum, nam consequatur? Vitae cum quasi quibusdam cumque culpa magni omnis repellat eius! Repellat aperiam in vero illum, porro ratione ea sunt excepturi fugiat? Optio dolor et labore reprehenderit? Architecto ab deserunt, laudantium magnam odio enim ipsum, consequatur necessitatibus sequi delectus nam aperiam ipsa. At impedit blanditiis, consequatur rerum assumenda inventore magni delectus deserunt unde, autem nulla architecto earum voluptatum eos officiis rem qui quas necessitatibus commodi laboriosam veniam exercitationem incidunt. Provident, dicta sunt repellat libero aperiam earum quis facere molestiae architecto beatae expedita magni porro cumque sit ullam? Obcaecati itaque, est quod exercitationem inventore tempore aliquam sapiente doloremque, quis vitae possimus error eaque alias corrupti suscipit labore earum! Omnis nam necessitatibus culpa excepturi quam nostrum, consequatur rerum inventore aliquid? Iure laudantium at tempore adipisci, molestias et! At ex beatae, delectus debitis totam ad iste doloribus nemo possimus! Animi, quaerat, recusandae dolores perferendis nobis impedit soluta, est cumque fuga quam dignissimos minima quia dolorem reiciendis porro adipisci quo vero incidunt iure iste accusantium. Delectus aut sunt autem pariatur repellat, eveniet vero soluta laudantium quidem, possimus dolore quisquam, nam voluptatem dignissimos sint optio maiores illum earum aliquam quaerat. Iusto dicta eaque optio odio veniam reprehenderit rem autem cumque iure corrupti.
      </p>
    </div>
  )
}
