import React from 'react'

export default function Home() {
  return (
    // This is a sample Home Page text
    <div style={{ paddingRight: "10vw", paddingLeft: "10vw", textAlign: "justify" }}>
      <h2>Home Page</h2>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita, debitis optio ab quod corrupti sequi? Accusamus, doloribus fugit aliquam deleniti minus ab impedit autem laboriosam, adipisci provident fuga recusandae rerum non nobis! Placeat harum accusantium impedit optio facilis laboriosam reprehenderit maxime corrupti laudantium aliquid sint possimus aut voluptate nisi ut aspernatur, ad quos corporis eius fugit veritatis quasi necessitatibus consectetur. Harum ullam iusto est modi reiciendis nam, deleniti iste! Voluptas molestiae repellat vel adipisci ipsum eligendi recusandae sapiente aliquam iusto veritatis culpa sequi doloribus magnam totam cupiditate nam deserunt, aut nemo ratione illo. Blanditiis ad nulla exercitationem maiores facilis reiciendis.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi id ipsum provident, sed, distinctio error repudiandae fugit numquam deleniti obcaecati porro aperiam. Dignissimos expedita distinctio illum possimus sit quod est mollitia repellendus iusto explicabo, impedit fugiat quis aperiam debitis molestias architecto ipsa, recusandae sequi voluptatibus deleniti. Exercitationem dignissimos nam dolor perspiciatis enim tempore, dicta modi. Quasi deserunt, modi impedit consectetur non ex, aperiam tenetur mollitia ratione, quia voluptates. Explicabo cumque iusto necessitatibus deleniti magnam nisi totam dolorem eum nobis maiores corrupti ex aut modi, voluptatum officiis voluptas repellat debitis enim, id culpa dolore, tenetur quam vel. Possimus natus eaque, recusandae itaque ipsa eveniet est incidunt voluptates, obcaecati, ea corrupti alias? Suscipit error rerum corrupti ipsam dolorem officia obcaecati quo? Unde, exercitationem! Facere, temporibus? Veniam sunt iste, alias odit quam accusantium officiis labore. Non amet inventore recusandae ut aliquam quisquam, laboriosam odio ratione distinctio unde labore beatae, repudiandae facilis laborum nemo quae. Assumenda qui ipsum neque quis ab ut sed? Repellendus pariatur possimus sapiente, praesentium vero quibusdam numquam saepe iste provident reprehenderit similique cum nulla corporis facilis temporibus aut iure. Sapiente nisi error debitis alias ut ducimus perspiciatis natus quibusdam esse corporis repellat consectetur mollitia iste nemo, temporibus enim provident reprehenderit maiores eaque non neque molestias totam cum ratione. Omnis itaque hic temporibus totam animi! Adipisci, quod ipsa. Quasi excepturi, minima commodi voluptatum necessitatibus ipsum quae impedit veniam omnis, officiis nemo vel quidem nobis, corrupti distinctio ipsam. Earum doloribus amet voluptatem dolores iste, cupiditate expedita perferendis sint porro tempora libero? Doloribus?
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam voluptas corrupti blanditiis accusantium in laboriosam unde consequuntur labore vel, quia incidunt recusandae impedit velit ratione magnam cupiditate ex laborum. Consequatur, asperiores quia fugit quis repellendus quo, nobis libero ex delectus nam vitae veritatis hic iure! Mollitia repellat eos esse distinctio dolorem assumenda laboriosam. Repellat possimus inventore libero rerum veniam architecto magni officiis quis, saepe cupiditate, adipisci itaque dicta. Nulla accusamus non nobis vero saepe id quibusdam dignissimos dolor nisi? Numquam, natus consequuntur minus voluptas ullam modi neque, repudiandae temporibus animi amet atque doloribus error illum laboriosam? Quis architecto magnam, reiciendis voluptates quas nisi repellat ducimus optio odit suscipit eos veniam autem earum deleniti aspernatur eaque dolorem quia aliquid totam facilis, aut unde modi at? Fuga hic dolorum porro voluptate repellendus.
      </p>
    </div>
  )
}
